DEFAULT_CONTEXT_WINDOW = 2048

DEFAULT_KEEP_ALIVE = "30m"

DEFAULT_TIMEOUT = 60

DEFAULT_JSON_TEMPERATURE = 0.0

DEFAULT_CHAT_TEMPERATURE = 0.7

DEFAULT_CODING_TEMPERATURE = 0.1

DEFAULT_FAST_TEMPERATURE = 0.2
