"""add livekit room tracking fields

Revision ID: 198613af8b62
Revises: 06c50292e0f2
Create Date: 2026-08-04 05:30:48.016399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '198613af8b62'
down_revision: Union[str, Sequence[str], None] = '06c50292e0f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_rooms', sa.Column('livekit_url', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_rooms', 'livekit_url')
    # ### end Alembic commands ###
