"""add interview transcripts table

Revision ID: 21395017b126
Revises: 17f7741aabbc
Create Date: 2026-08-05 01:13:38.448352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21395017b126'
down_revision: Union[str, Sequence[str], None] = '17f7741aabbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interview_transcripts', 'start_time',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('interview_transcripts', 'end_time',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.create_index(op.f('ix_interview_transcripts_interview_id'), 'interview_transcripts', ['interview_id'], unique=False)
    op.create_index(op.f('ix_interview_transcripts_question_id'), 'interview_transcripts', ['question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interview_transcripts_question_id'), table_name='interview_transcripts')
    op.drop_index(op.f('ix_interview_transcripts_interview_id'), table_name='interview_transcripts')
    op.alter_column('interview_transcripts', 'end_time',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('interview_transcripts', 'start_time',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###
