"""add interview_id to coding_submissions

Revision ID: 220d383b6b9a
Revises: 8ec10ccfab72
Create Date: 2026-07-29 00:54:05.705022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '220d383b6b9a'
down_revision: Union[str, Sequence[str], None] = '8ec10ccfab72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coding_submissions', sa.Column('interview_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'coding_submissions', 'coding_interviews', ['interview_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'coding_submissions', type_='foreignkey')
    op.drop_column('coding_submissions', 'interview_id')
    # ### end Alembic commands ###
