"""add interview session fields

Revision ID: 300dee222e45
Revises: 8bcb811803e4
Create Date: 2026-07-14 03:39:28.826548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '300dee222e45'
down_revision: Union[str, Sequence[str], None] = '8bcb811803e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('status', sa.String(), nullable=False,server_default="pending"))
    op.add_column('interviews', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('interviews', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('interviews', sa.Column('duration', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'duration')
    op.drop_column('interviews', 'completed_at')
    op.drop_column('interviews', 'started_at')
    op.drop_column('interviews', 'status')
    # ### end Alembic commands ###
