"""add role and difficulty to interviews

Revision ID: 67c96ab13061
Revises: 57267620c166
Create Date: 2026-07-12 02:53:11.439879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67c96ab13061'
down_revision: Union[str, Sequence[str], None] = '57267620c166'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('role', sa.String(), nullable=False))
    op.add_column('interviews', sa.Column('difficulty', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'difficulty')
    op.drop_column('interviews', 'role')
    # ### end Alembic commands ###
