"""add prompt execution analytics fields

Revision ID: 9f61bf3eb841
Revises: 381148e6e1da
Create Date: 2026-08-03 06:44:05.447407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f61bf3eb841'
down_revision: Union[str, Sequence[str], None] = '381148e6e1da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prompt_execution_logs_id'), table_name='prompt_execution_logs')
    op.drop_table('prompt_execution_logs')
    op.alter_column('coding_interviews', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('coding_interviews', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('coding_interviews', 'language',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'python'::character varying"))
    op.alter_column('coding_interviews', 'difficulty',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('coding_interviews', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.create_foreign_key(None, 'coding_interviews', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('coding_questions', sa.Column('solution', sa.Text(), nullable=True))
    op.alter_column('coding_questions', 'coding_interview_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('coding_questions', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('coding_questions', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('coding_questions', 'difficulty',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(None, 'coding_questions', 'coding_interviews', ['coding_interview_id'], ['id'], ondelete='CASCADE')
    op.drop_column('coding_questions', 'solution_code')
    op.drop_column('coding_questions', 'created_at')
    op.alter_column('coding_submissions', 'question_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('coding_submissions', 'language',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('coding_submissions', 'code',
               existing_type=sa.TEXT(),
               nullable=False)
    op.add_column('prompt_executions', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('prompt_executions', sa.Column('error', sa.Text(), nullable=True))
    op.add_column('prompt_executions', sa.Column('tokens_used', sa.Integer(), nullable=True))
    op.alter_column('prompt_executions', 'success',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('prompt_executions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.create_index(op.f('ix_prompt_executions_user_id'), 'prompt_executions', ['user_id'], unique=False)
    op.create_foreign_key(None, 'prompt_executions', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_prompts_id'), 'prompts', ['id'], unique=False)
    op.create_index(op.f('ix_prompts_is_active'), 'prompts', ['is_active'], unique=False)
    op.create_unique_constraint('uq_prompt_name_version', 'prompts', ['name', 'version'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_prompt_name_version', 'prompts', type_='unique')
    op.drop_index(op.f('ix_prompts_is_active'), table_name='prompts')
    op.drop_index(op.f('ix_prompts_id'), table_name='prompts')
    op.drop_constraint(None, 'prompt_executions', type_='foreignkey')
    op.drop_index(op.f('ix_prompt_executions_user_id'), table_name='prompt_executions')
    op.alter_column('prompt_executions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('prompt_executions', 'success',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('prompt_executions', 'tokens_used')
    op.drop_column('prompt_executions', 'error')
    op.drop_column('prompt_executions', 'user_id')
    op.alter_column('coding_submissions', 'code',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('coding_submissions', 'language',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('coding_submissions', 'question_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('coding_questions', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('coding_questions', sa.Column('solution_code', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'coding_questions', type_='foreignkey')
    op.alter_column('coding_questions', 'difficulty',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('coding_questions', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('coding_questions', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('coding_questions', 'coding_interview_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('coding_questions', 'solution')
    op.drop_constraint(None, 'coding_interviews', type_='foreignkey')
    op.alter_column('coding_interviews', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('coding_interviews', 'difficulty',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('coding_interviews', 'language',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'python'::character varying"))
    op.alter_column('coding_interviews', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('coding_interviews', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('prompt_execution_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('prompt_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('input_data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('output_data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('model', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('provider', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('tokens_used', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('execution_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], name=op.f('prompt_execution_logs_prompt_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('prompt_execution_logs_pkey'))
    )
    op.create_index(op.f('ix_prompt_execution_logs_id'), 'prompt_execution_logs', ['id'], unique=False)
    # ### end Alembic commands ###
