"""add coding interview progress fields

Revision ID: bbbac09af119
Revises: 0ccfca473092
Create Date: 2026-07-24 06:18:56.562395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbbac09af119'
down_revision: Union[str, Sequence[str], None] = '0ccfca473092'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coding_interviews', sa.Column('current_question', sa.Integer(), server_default='0', nullable=False))
    op.add_column('coding_interviews', sa.Column('answered_questions', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coding_interviews', 'answered_questions')
    op.drop_column('coding_interviews', 'current_question')
    # ### end Alembic commands ###
