"""add function name to coding questions

Revision ID: d955dff7fbf1
Revises: 0a26cfbb9286
Create Date: 2026-07-28 13:56:35.144054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd955dff7fbf1'
down_revision: Union[str, Sequence[str], None] = '0a26cfbb9286'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coding_questions', sa.Column('function_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coding_questions', 'function_name')
    # ### end Alembic commands ###
