"""add interview_id to coding_submissions

Revision ID: ec8436767dbd
Revises: 220d383b6b9a
Create Date: 2026-07-29 00:54:51.389610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec8436767dbd'
down_revision: Union[str, Sequence[str], None] = '220d383b6b9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('coding_submissions', 'interview_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('coding_submissions', 'interview_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
